// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="lec10ex1,hls_ip_2020_1,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xqvu7p-flrb2104-1-i,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.893000,HLS_SYN_LAT=67,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=3,HLS_SYN_FF=407,HLS_SYN_LUT=239,HLS_VERSION=2020_1}" *)

module lec10ex1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        y,
        y_ap_vld,
        c_address0,
        c_ce0,
        c_q0,
        x
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] y;
output   y_ap_vld;
output  [3:0] c_address0;
output   c_ce0;
input  [31:0] c_q0;
input  [31:0] x;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg y_ap_vld;
reg c_ce0;

(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [3:0] arr_address0;
reg    arr_ce0;
reg    arr_we0;
reg   [31:0] arr_d0;
wire   [31:0] arr_q0;
wire  signed [31:0] sext_ln12_fu_133_p1;
reg  signed [31:0] sext_ln12_reg_180;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln14_fu_145_p2;
reg   [0:0] icmp_ln14_reg_189;
wire   [0:0] tmp_fu_137_p3;
wire    ap_CS_fsm_state3;
wire   [4:0] grp_fu_126_p2;
reg   [4:0] i_reg_208;
reg  signed [31:0] c_load_reg_213;
wire    ap_CS_fsm_state4;
wire   [31:0] grp_fu_164_p2;
reg   [31:0] mul_ln24_reg_218;
wire    ap_CS_fsm_state6;
wire   [31:0] sum_fu_169_p2;
wire    ap_CS_fsm_state7;
reg   [31:0] sum_0_reg_91;
wire  signed [4:0] ap_phi_mux_i_0_phi_fu_108_p4;
reg  signed [4:0] i_0_reg_104;
reg  signed [31:0] data_0_reg_116;
wire   [63:0] zext_ln21_fu_151_p1;
wire   [63:0] zext_ln21_1_fu_156_p1;
wire   [63:0] zext_ln24_fu_160_p1;
reg  signed [4:0] grp_fu_126_p0;
wire    ap_CS_fsm_state5;
reg   [6:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 7'd1;
end

lec10ex1_arr #(
    .DataWidth( 32 ),
    .AddressRange( 11 ),
    .AddressWidth( 4 ))
arr_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(arr_address0),
    .ce0(arr_ce0),
    .we0(arr_we0),
    .d0(arr_d0),
    .q0(arr_q0)
);

lec10ex1_mul_32s_bkb #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
lec10ex1_mul_32s_bkb_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(c_load_reg_213),
    .din1(data_0_reg_116),
    .ce(1'b1),
    .dout(grp_fu_164_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln14_reg_189 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        data_0_reg_116 <= arr_q0;
    end else if (((tmp_fu_137_p3 == 1'd0) & (icmp_ln14_fu_145_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        data_0_reg_116 <= x;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        i_0_reg_104 <= i_reg_208;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_0_reg_104 <= 5'd10;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        sum_0_reg_91 <= sum_fu_169_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        sum_0_reg_91 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        c_load_reg_213 <= c_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_reg_208 <= grp_fu_126_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_137_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        icmp_ln14_reg_189 <= icmp_ln14_fu_145_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        mul_ln24_reg_218 <= grp_fu_164_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        sext_ln12_reg_180 <= sext_ln12_fu_133_p1;
    end
end

always @ (*) begin
    if (((tmp_fu_137_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_137_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        arr_address0 = zext_ln21_1_fu_156_p1;
    end else if (((tmp_fu_137_p3 == 1'd0) & (icmp_ln14_fu_145_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        arr_address0 = 4'd0;
    end else if (((tmp_fu_137_p3 == 1'd0) & (icmp_ln14_fu_145_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        arr_address0 = zext_ln21_fu_151_p1;
    end else begin
        arr_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((tmp_fu_137_p3 == 1'd0) & (icmp_ln14_fu_145_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((tmp_fu_137_p3 == 1'd0) & (icmp_ln14_fu_145_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
        arr_ce0 = 1'b1;
    end else begin
        arr_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        arr_d0 = arr_q0;
    end else if (((tmp_fu_137_p3 == 1'd0) & (icmp_ln14_fu_145_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        arr_d0 = x;
    end else begin
        arr_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln14_reg_189 == 1'd0) & (1'b1 == ap_CS_fsm_state3)) | ((tmp_fu_137_p3 == 1'd0) & (icmp_ln14_fu_145_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
        arr_we0 = 1'b1;
    end else begin
        arr_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        c_ce0 = 1'b1;
    end else begin
        c_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_126_p0 = i_0_reg_104;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_126_p0 = ap_phi_mux_i_0_phi_fu_108_p4;
    end else begin
        grp_fu_126_p0 = 'bx;
    end
end

always @ (*) begin
    if (((tmp_fu_137_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        y_ap_vld = 1'b1;
    end else begin
        y_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((tmp_fu_137_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_phi_mux_i_0_phi_fu_108_p4 = i_0_reg_104;

assign c_address0 = zext_ln24_fu_160_p1;

assign grp_fu_126_p2 = ($signed(grp_fu_126_p0) + $signed(5'd31));

assign icmp_ln14_fu_145_p2 = ((i_0_reg_104 == 5'd0) ? 1'b1 : 1'b0);

assign sext_ln12_fu_133_p1 = i_0_reg_104;

assign sum_fu_169_p2 = (mul_ln24_reg_218 + sum_0_reg_91);

assign tmp_fu_137_p3 = i_0_reg_104[32'd4];

assign y = sum_0_reg_91;

assign zext_ln21_1_fu_156_p1 = $unsigned(sext_ln12_reg_180);

assign zext_ln21_fu_151_p1 = grp_fu_126_p2;

assign zext_ln24_fu_160_p1 = $unsigned(sext_ln12_reg_180);

endmodule //lec10ex1
