// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "assignment_4_ap.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic assignment_4_ap::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic assignment_4_ap::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<22> assignment_4_ap::ap_ST_fsm_state1 = "1";
const sc_lv<22> assignment_4_ap::ap_ST_fsm_state2 = "10";
const sc_lv<22> assignment_4_ap::ap_ST_fsm_state3 = "100";
const sc_lv<22> assignment_4_ap::ap_ST_fsm_state4 = "1000";
const sc_lv<22> assignment_4_ap::ap_ST_fsm_state5 = "10000";
const sc_lv<22> assignment_4_ap::ap_ST_fsm_state6 = "100000";
const sc_lv<22> assignment_4_ap::ap_ST_fsm_state7 = "1000000";
const sc_lv<22> assignment_4_ap::ap_ST_fsm_state8 = "10000000";
const sc_lv<22> assignment_4_ap::ap_ST_fsm_state9 = "100000000";
const sc_lv<22> assignment_4_ap::ap_ST_fsm_state10 = "1000000000";
const sc_lv<22> assignment_4_ap::ap_ST_fsm_state11 = "10000000000";
const sc_lv<22> assignment_4_ap::ap_ST_fsm_state12 = "100000000000";
const sc_lv<22> assignment_4_ap::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<22> assignment_4_ap::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<22> assignment_4_ap::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<22> assignment_4_ap::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<22> assignment_4_ap::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<22> assignment_4_ap::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<22> assignment_4_ap::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<22> assignment_4_ap::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<22> assignment_4_ap::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<22> assignment_4_ap::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<32> assignment_4_ap::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> assignment_4_ap::ap_const_lv32_1 = "1";
const sc_lv<1> assignment_4_ap::ap_const_lv1_0 = "0";
const sc_lv<32> assignment_4_ap::ap_const_lv32_2 = "10";
const sc_lv<4> assignment_4_ap::ap_const_lv4_0 = "0000";
const sc_lv<32> assignment_4_ap::ap_const_lv32_15 = "10101";
const sc_lv<4> assignment_4_ap::ap_const_lv4_C = "1100";
const sc_lv<4> assignment_4_ap::ap_const_lv4_1 = "1";
const sc_lv<1> assignment_4_ap::ap_const_lv1_1 = "1";
const bool assignment_4_ap::ap_const_boolean_1 = true;

assignment_4_ap::assignment_4_ap(sc_module_name name) : sc_module(name), mVcdFile(0) {
    assignment_4_ap_sbkb_U1 = new assignment_4_ap_sbkb<1,20,16,16,16>("assignment_4_ap_sbkb_U1");
    assignment_4_ap_sbkb_U1->clk(ap_clk);
    assignment_4_ap_sbkb_U1->reset(ap_rst);
    assignment_4_ap_sbkb_U1->start(grp_fu_166_ap_start);
    assignment_4_ap_sbkb_U1->done(grp_fu_166_ap_done);
    assignment_4_ap_sbkb_U1->din0(array_a_cpp_V_q0);
    assignment_4_ap_sbkb_U1->din1(array_b_cpp_V_q0);
    assignment_4_ap_sbkb_U1->ce(ap_var_for_const0);
    assignment_4_ap_sbkb_U1->dout(grp_fu_166_p2);
    assignment_4_ap_scud_U2 = new assignment_4_ap_scud<1,20,16,16,16>("assignment_4_ap_scud_U2");
    assignment_4_ap_scud_U2->clk(ap_clk);
    assignment_4_ap_scud_U2->reset(ap_rst);
    assignment_4_ap_scud_U2->start(grp_fu_173_ap_start);
    assignment_4_ap_scud_U2->done(grp_fu_173_ap_done);
    assignment_4_ap_scud_U2->din0(array_a_cpp_V_q0);
    assignment_4_ap_scud_U2->din1(array_b_cpp_V_q0);
    assignment_4_ap_scud_U2->ce(ap_var_for_const0);
    assignment_4_ap_scud_U2->dout(grp_fu_173_p2);
    assignment_4_ap_mdEe_U3 = new assignment_4_ap_mdEe<1,1,16,16,16>("assignment_4_ap_mdEe_U3");
    assignment_4_ap_mdEe_U3->din0(array_a_cpp_V_q0);
    assignment_4_ap_mdEe_U3->din1(array_b_cpp_V_q0);
    assignment_4_ap_mdEe_U3->dout(mul_ln68_fu_180_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_V_address0);
    sensitive << ( zext_ln11_reg_195 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_add_V_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_add_V_d0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( add_ln68_fu_152_p0 );
    sensitive << ( add_ln68_fu_152_p1 );

    SC_METHOD(thread_add_V_we0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_add_ln68_fu_152_p0);
    sensitive << ( array_a_cpp_V_q0 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_add_ln68_fu_152_p1);
    sensitive << ( array_b_cpp_V_q0 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state22);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln9_fu_134_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln9_fu_134_p2 );

    SC_METHOD(thread_array_a_cpp_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( zext_ln11_fu_146_p1 );

    SC_METHOD(thread_array_a_cpp_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_array_b_cpp_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( zext_ln11_fu_146_p1 );

    SC_METHOD(thread_array_b_cpp_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_div_V_address0);
    sensitive << ( zext_ln11_reg_195 );
    sensitive << ( ap_CS_fsm_state22 );

    SC_METHOD(thread_div_V_ce0);
    sensitive << ( ap_CS_fsm_state22 );

    SC_METHOD(thread_div_V_d0);
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( grp_fu_166_p2 );

    SC_METHOD(thread_div_V_we0);
    sensitive << ( ap_CS_fsm_state22 );

    SC_METHOD(thread_grp_fu_166_ap_start);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_grp_fu_173_ap_start);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_i_fu_140_p2);
    sensitive << ( i_0_reg_123 );

    SC_METHOD(thread_icmp_ln9_fu_134_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_reg_123 );

    SC_METHOD(thread_mod_V_address0);
    sensitive << ( zext_ln11_reg_195 );
    sensitive << ( ap_CS_fsm_state22 );

    SC_METHOD(thread_mod_V_ce0);
    sensitive << ( ap_CS_fsm_state22 );

    SC_METHOD(thread_mod_V_d0);
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( grp_fu_173_p2 );

    SC_METHOD(thread_mod_V_we0);
    sensitive << ( ap_CS_fsm_state22 );

    SC_METHOD(thread_mul_V_address0);
    sensitive << ( zext_ln11_reg_195 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_mul_V_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_mul_V_d0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( mul_ln68_fu_180_p2 );

    SC_METHOD(thread_mul_V_we0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_sub_V_address0);
    sensitive << ( zext_ln11_reg_195 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_sub_V_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_sub_V_d0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( sub_ln68_fu_159_p0 );
    sensitive << ( sub_ln68_fu_159_p1 );

    SC_METHOD(thread_sub_V_we0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_sub_ln68_fu_159_p0);
    sensitive << ( array_a_cpp_V_q0 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_sub_ln68_fu_159_p1);
    sensitive << ( array_b_cpp_V_q0 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_zext_ln11_fu_146_p1);
    sensitive << ( i_0_reg_123 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln9_fu_134_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "0000000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "assignment_4_ap_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, array_a_cpp_V_address0, "(port)array_a_cpp_V_address0");
    sc_trace(mVcdFile, array_a_cpp_V_ce0, "(port)array_a_cpp_V_ce0");
    sc_trace(mVcdFile, array_a_cpp_V_q0, "(port)array_a_cpp_V_q0");
    sc_trace(mVcdFile, array_b_cpp_V_address0, "(port)array_b_cpp_V_address0");
    sc_trace(mVcdFile, array_b_cpp_V_ce0, "(port)array_b_cpp_V_ce0");
    sc_trace(mVcdFile, array_b_cpp_V_q0, "(port)array_b_cpp_V_q0");
    sc_trace(mVcdFile, add_V_address0, "(port)add_V_address0");
    sc_trace(mVcdFile, add_V_ce0, "(port)add_V_ce0");
    sc_trace(mVcdFile, add_V_we0, "(port)add_V_we0");
    sc_trace(mVcdFile, add_V_d0, "(port)add_V_d0");
    sc_trace(mVcdFile, sub_V_address0, "(port)sub_V_address0");
    sc_trace(mVcdFile, sub_V_ce0, "(port)sub_V_ce0");
    sc_trace(mVcdFile, sub_V_we0, "(port)sub_V_we0");
    sc_trace(mVcdFile, sub_V_d0, "(port)sub_V_d0");
    sc_trace(mVcdFile, mul_V_address0, "(port)mul_V_address0");
    sc_trace(mVcdFile, mul_V_ce0, "(port)mul_V_ce0");
    sc_trace(mVcdFile, mul_V_we0, "(port)mul_V_we0");
    sc_trace(mVcdFile, mul_V_d0, "(port)mul_V_d0");
    sc_trace(mVcdFile, div_V_address0, "(port)div_V_address0");
    sc_trace(mVcdFile, div_V_ce0, "(port)div_V_ce0");
    sc_trace(mVcdFile, div_V_we0, "(port)div_V_we0");
    sc_trace(mVcdFile, div_V_d0, "(port)div_V_d0");
    sc_trace(mVcdFile, mod_V_address0, "(port)mod_V_address0");
    sc_trace(mVcdFile, mod_V_ce0, "(port)mod_V_ce0");
    sc_trace(mVcdFile, mod_V_we0, "(port)mod_V_we0");
    sc_trace(mVcdFile, mod_V_d0, "(port)mod_V_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, i_fu_140_p2, "i_fu_140_p2");
    sc_trace(mVcdFile, i_reg_190, "i_reg_190");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, zext_ln11_fu_146_p1, "zext_ln11_fu_146_p1");
    sc_trace(mVcdFile, zext_ln11_reg_195, "zext_ln11_reg_195");
    sc_trace(mVcdFile, icmp_ln9_fu_134_p2, "icmp_ln9_fu_134_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, i_0_reg_123, "i_0_reg_123");
    sc_trace(mVcdFile, ap_CS_fsm_state22, "ap_CS_fsm_state22");
    sc_trace(mVcdFile, mul_ln68_fu_180_p2, "mul_ln68_fu_180_p2");
    sc_trace(mVcdFile, grp_fu_166_p2, "grp_fu_166_p2");
    sc_trace(mVcdFile, grp_fu_173_p2, "grp_fu_173_p2");
    sc_trace(mVcdFile, add_ln68_fu_152_p0, "add_ln68_fu_152_p0");
    sc_trace(mVcdFile, add_ln68_fu_152_p1, "add_ln68_fu_152_p1");
    sc_trace(mVcdFile, sub_ln68_fu_159_p0, "sub_ln68_fu_159_p0");
    sc_trace(mVcdFile, sub_ln68_fu_159_p1, "sub_ln68_fu_159_p1");
    sc_trace(mVcdFile, grp_fu_166_ap_start, "grp_fu_166_ap_start");
    sc_trace(mVcdFile, grp_fu_166_ap_done, "grp_fu_166_ap_done");
    sc_trace(mVcdFile, grp_fu_173_ap_start, "grp_fu_173_ap_start");
    sc_trace(mVcdFile, grp_fu_173_ap_done, "grp_fu_173_ap_done");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("assignment_4_ap.hdltvin.dat");
    mHdltvoutHandle.open("assignment_4_ap.hdltvout.dat");
}

assignment_4_ap::~assignment_4_ap() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete assignment_4_ap_sbkb_U1;
    delete assignment_4_ap_scud_U2;
    delete assignment_4_ap_mdEe_U3;
}

void assignment_4_ap::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void assignment_4_ap::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
        i_0_reg_123 = i_reg_190.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_reg_123 = ap_const_lv4_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_reg_190 = i_fu_140_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln9_fu_134_p2.read(), ap_const_lv1_0))) {
        zext_ln11_reg_195 = zext_ln11_fu_146_p1.read();
    }
}

void assignment_4_ap::thread_add_V_address0() {
    add_V_address0 =  (sc_lv<4>) (zext_ln11_reg_195.read());
}

void assignment_4_ap::thread_add_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        add_V_ce0 = ap_const_logic_1;
    } else {
        add_V_ce0 = ap_const_logic_0;
    }
}

void assignment_4_ap::thread_add_V_d0() {
    add_V_d0 = (!add_ln68_fu_152_p0.read().is_01() || !add_ln68_fu_152_p1.read().is_01())? sc_lv<16>(): (sc_bigint<16>(add_ln68_fu_152_p0.read()) + sc_bigint<16>(add_ln68_fu_152_p1.read()));
}

void assignment_4_ap::thread_add_V_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        add_V_we0 = ap_const_logic_1;
    } else {
        add_V_we0 = ap_const_logic_0;
    }
}

void assignment_4_ap::thread_add_ln68_fu_152_p0() {
    add_ln68_fu_152_p0 = array_a_cpp_V_q0.read();
}

void assignment_4_ap::thread_add_ln68_fu_152_p1() {
    add_ln68_fu_152_p1 = array_b_cpp_V_q0.read();
}

void assignment_4_ap::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void assignment_4_ap::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void assignment_4_ap::thread_ap_CS_fsm_state22() {
    ap_CS_fsm_state22 = ap_CS_fsm.read()[21];
}

void assignment_4_ap::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void assignment_4_ap::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln9_fu_134_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void assignment_4_ap::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void assignment_4_ap::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln9_fu_134_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void assignment_4_ap::thread_array_a_cpp_V_address0() {
    array_a_cpp_V_address0 =  (sc_lv<4>) (zext_ln11_fu_146_p1.read());
}

void assignment_4_ap::thread_array_a_cpp_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        array_a_cpp_V_ce0 = ap_const_logic_1;
    } else {
        array_a_cpp_V_ce0 = ap_const_logic_0;
    }
}

void assignment_4_ap::thread_array_b_cpp_V_address0() {
    array_b_cpp_V_address0 =  (sc_lv<4>) (zext_ln11_fu_146_p1.read());
}

void assignment_4_ap::thread_array_b_cpp_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        array_b_cpp_V_ce0 = ap_const_logic_1;
    } else {
        array_b_cpp_V_ce0 = ap_const_logic_0;
    }
}

void assignment_4_ap::thread_div_V_address0() {
    div_V_address0 =  (sc_lv<4>) (zext_ln11_reg_195.read());
}

void assignment_4_ap::thread_div_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
        div_V_ce0 = ap_const_logic_1;
    } else {
        div_V_ce0 = ap_const_logic_0;
    }
}

void assignment_4_ap::thread_div_V_d0() {
    div_V_d0 = grp_fu_166_p2.read();
}

void assignment_4_ap::thread_div_V_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
        div_V_we0 = ap_const_logic_1;
    } else {
        div_V_we0 = ap_const_logic_0;
    }
}

void assignment_4_ap::thread_grp_fu_166_ap_start() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        grp_fu_166_ap_start = ap_const_logic_1;
    } else {
        grp_fu_166_ap_start = ap_const_logic_0;
    }
}

void assignment_4_ap::thread_grp_fu_173_ap_start() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        grp_fu_173_ap_start = ap_const_logic_1;
    } else {
        grp_fu_173_ap_start = ap_const_logic_0;
    }
}

void assignment_4_ap::thread_i_fu_140_p2() {
    i_fu_140_p2 = (!i_0_reg_123.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i_0_reg_123.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void assignment_4_ap::thread_icmp_ln9_fu_134_p2() {
    icmp_ln9_fu_134_p2 = (!i_0_reg_123.read().is_01() || !ap_const_lv4_C.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_123.read() == ap_const_lv4_C);
}

void assignment_4_ap::thread_mod_V_address0() {
    mod_V_address0 =  (sc_lv<4>) (zext_ln11_reg_195.read());
}

void assignment_4_ap::thread_mod_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
        mod_V_ce0 = ap_const_logic_1;
    } else {
        mod_V_ce0 = ap_const_logic_0;
    }
}

void assignment_4_ap::thread_mod_V_d0() {
    mod_V_d0 = grp_fu_173_p2.read();
}

void assignment_4_ap::thread_mod_V_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
        mod_V_we0 = ap_const_logic_1;
    } else {
        mod_V_we0 = ap_const_logic_0;
    }
}

void assignment_4_ap::thread_mul_V_address0() {
    mul_V_address0 =  (sc_lv<4>) (zext_ln11_reg_195.read());
}

void assignment_4_ap::thread_mul_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mul_V_ce0 = ap_const_logic_1;
    } else {
        mul_V_ce0 = ap_const_logic_0;
    }
}

void assignment_4_ap::thread_mul_V_d0() {
    mul_V_d0 = mul_ln68_fu_180_p2.read();
}

void assignment_4_ap::thread_mul_V_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mul_V_we0 = ap_const_logic_1;
    } else {
        mul_V_we0 = ap_const_logic_0;
    }
}

void assignment_4_ap::thread_sub_V_address0() {
    sub_V_address0 =  (sc_lv<4>) (zext_ln11_reg_195.read());
}

void assignment_4_ap::thread_sub_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        sub_V_ce0 = ap_const_logic_1;
    } else {
        sub_V_ce0 = ap_const_logic_0;
    }
}

void assignment_4_ap::thread_sub_V_d0() {
    sub_V_d0 = (!sub_ln68_fu_159_p0.read().is_01() || !sub_ln68_fu_159_p1.read().is_01())? sc_lv<16>(): (sc_bigint<16>(sub_ln68_fu_159_p0.read()) - sc_bigint<16>(sub_ln68_fu_159_p1.read()));
}

void assignment_4_ap::thread_sub_V_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        sub_V_we0 = ap_const_logic_1;
    } else {
        sub_V_we0 = ap_const_logic_0;
    }
}

void assignment_4_ap::thread_sub_ln68_fu_159_p0() {
    sub_ln68_fu_159_p0 = array_a_cpp_V_q0.read();
}

void assignment_4_ap::thread_sub_ln68_fu_159_p1() {
    sub_ln68_fu_159_p1 = array_b_cpp_V_q0.read();
}

void assignment_4_ap::thread_zext_ln11_fu_146_p1() {
    zext_ln11_fu_146_p1 = esl_zext<64,4>(i_0_reg_123.read());
}

void assignment_4_ap::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln9_fu_134_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXXXXXXXXXXXXXXXX";
            break;
    }
}

void assignment_4_ap::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"array_a_cpp_V_address0\" :  \"" << array_a_cpp_V_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"array_a_cpp_V_ce0\" :  \"" << array_a_cpp_V_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"array_a_cpp_V_q0\" :  \"" << array_a_cpp_V_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"array_b_cpp_V_address0\" :  \"" << array_b_cpp_V_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"array_b_cpp_V_ce0\" :  \"" << array_b_cpp_V_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"array_b_cpp_V_q0\" :  \"" << array_b_cpp_V_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"add_V_address0\" :  \"" << add_V_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"add_V_ce0\" :  \"" << add_V_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"add_V_we0\" :  \"" << add_V_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"add_V_d0\" :  \"" << add_V_d0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sub_V_address0\" :  \"" << sub_V_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sub_V_ce0\" :  \"" << sub_V_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sub_V_we0\" :  \"" << sub_V_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sub_V_d0\" :  \"" << sub_V_d0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"mul_V_address0\" :  \"" << mul_V_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"mul_V_ce0\" :  \"" << mul_V_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"mul_V_we0\" :  \"" << mul_V_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"mul_V_d0\" :  \"" << mul_V_d0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"div_V_address0\" :  \"" << div_V_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"div_V_ce0\" :  \"" << div_V_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"div_V_we0\" :  \"" << div_V_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"div_V_d0\" :  \"" << div_V_d0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"mod_V_address0\" :  \"" << mod_V_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"mod_V_ce0\" :  \"" << mod_V_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"mod_V_we0\" :  \"" << mod_V_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"mod_V_d0\" :  \"" << mod_V_d0.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

